#!/bin/bash

#pandoc epub metadata ref: http://johnmacfarlane.net/pandoc/demo/example9/epub-metadata.html

FILE=$(cat $1)
STYLE_SHEET=$2

TITLE=$(echo $FILE | jq '.data.title' -r)
CREATOR=$(echo $FILE | jq '.data.author' -r)
DATE=$(echo $FILE | jq '.data.published' -r)
LANG=$(echo $FILE | jq '.data.language' -r)
SUBJ=$(echo $FILE | jq '.data.keywords[].name' -r)
DESC=$(echo $FILE | jq '.data.summary' -r)
COVER=$(echo $FILE | jq '.data.images[0].url' -r)

echo $STYLE_SHEET
