#!/bin/bash

F_PATH=$(realpath $1)
F_NAME=${F_PATH/.json/}
FILE=$(cat $F_PATH)

mkdir $F_NAME
pushd $F_NAME 
  TITLE=$(echo $FILE | jq '.data.title' -r)
  CREATOR=$(echo $FILE | jq '.data.authors[0].name' -r)
  CREATOR_URL=$(echo $FILE | jq '.data.authors[0].url' -r)
  ARTICLE_URL=$(echo $FILE | jq '.data.url' -r)
  DATE=$(echo $FILE | jq '.data.published' -r)
  LANG=$(echo $FILE | jq '.data.language' -r)
  SUBJ=$(echo $FILE | jq '.data.keywords[].name' -r)
  DESC=$(echo $FILE | jq '.data.description' -r)
  DESC=${DESC/null/}
  COVER=$(echo $FILE | jq '.data.images[0].url' -r)
  CONTENT=$(echo $FILE | jq '.data.content' -r)
  CSS=../../base.css

  echo $(realpath $CSS)

  if [ -z "$CONTENT" ] || [ "null" == "$CONTENT" ]; then
    echo "Artigo sem conteúdo"
    exit 
  fi

  CONTENT="<h1>$TITLE</h1>$CONTENT"

  if [ "$DESC" ] && [ "$DESC" != "null" ]; then
    CONTENT="<h1>Abstract</h1><blockquote><p>$DESC</p></blockquote>$CONTENT"
  fi

  CONTENT="$CONTENT<p><ul>"
  if [ "$CREATOR" ] && [ "$CREATOR" != "null" ]; then
    CONTENT="$CONTENT<li>Author: $CREATOR</li>"
  fi
  if [ "$CREATOR_URL" ] && [ "$CREATOR_URL" != "null" ]; then
    CONTENT="$CONTENT<li>Author url: $CREATOR_URL</li>"
  fi
  if [ "$DATE" ] && [ "$DATE" != "null" ]; then
    DATE=$(date +"%Y-%m-%d" -d @$(  echo "($DATE + 500) / 1000" | bc))
    CONTENT="$CONTENT<li>Date: $DATE</li>"
  fi
  if [ "$ARTICLE_URL" ] && [ "$ARTICLE_URL" != "null" ]; then
    CONTENT="$CONTENT<li><a href='$ARTICLE_URL'>$ARTICLE_URL</a></li>"
  fi
  CONTENT="$CONTENT</ul></p>"

  wget -q $COVER 
  COVER=$(baseName "$COVER")

  F_META=metadata.xml
  cat <<-EOF > $F_META
<dc:title>${TITLE/null/}</dc:title>
<dc:creator>${CREATOR/null/}</dc:creator>
<dc:date>${DATE/null/}</dc:date>
<dc:language>${LANG/null/}</dc:language>
<dc:subject>$SUBJ</dc:subject>
<dc:description>$DESC</dc:description>
EOF

  echo $CONTENT | pandoc -s --normalize --reference-links --chapters --epub-metadata=$F_META --epub-cover-image=$COVER --epub-stylesheet=$CSS -r html -w epub -o ${F_PATH/.json/.epub}
popd 

#rm -rf $F_NAME
